"""ISO country data shared by provider APIs and the OpenAI phone page.

HeroSMS returns provider-specific numeric country IDs, while OpenAI's list
box displays localized country names and dial codes. This table is the bridge
between those two identifiers.
"""


COUNTRY_BY_ISO2: dict[str, dict[str, str]] = {
    "AD": {"dial_code": "376", "en": "Andorra", "zh": "安道尔"},
    "AE": {"dial_code": "971", "en": "United Arab Emirates", "zh": "阿联酋"},
    "AF": {"dial_code": "93", "en": "Afghanistan", "zh": "阿富汗"},
    "AG": {"dial_code": "1", "en": "Antigua and Barbuda", "zh": "安提瓜和巴布达"},
    "AI": {"dial_code": "1", "en": "Anguilla", "zh": "安圭拉"},
    "AL": {"dial_code": "355", "en": "Albania", "zh": "阿尔巴尼亚"},
    "AM": {"dial_code": "374", "en": "Armenia", "zh": "亚美尼亚"},
    "AO": {"dial_code": "244", "en": "Angola", "zh": "安哥拉"},
    "AR": {"dial_code": "54", "en": "Argentina", "zh": "阿根廷"},
    "AS": {"dial_code": "1", "en": "American Samoa", "zh": "美属萨摩亚"},
    "AT": {"dial_code": "43", "en": "Austria", "zh": "奥地利"},
    "AU": {"dial_code": "61", "en": "Australia", "zh": "澳大利亚"},
    "AW": {"dial_code": "297", "en": "Aruba", "zh": "阿鲁巴"},
    "AZ": {"dial_code": "994", "en": "Azerbaijan", "zh": "阿塞拜疆"},
    "BA": {"dial_code": "387", "en": "Bosnia and Herzegovina", "zh": "波黑"},
    "BB": {"dial_code": "1", "en": "Barbados", "zh": "巴巴多斯"},
    "BD": {"dial_code": "880", "en": "Bangladesh", "zh": "孟加拉国"},
    "BE": {"dial_code": "32", "en": "Belgium", "zh": "比利时"},
    "BF": {"dial_code": "226", "en": "Burkina Faso", "zh": "布基纳法索"},
    "BG": {"dial_code": "359", "en": "Bulgaria", "zh": "保加利亚"},
    "BH": {"dial_code": "973", "en": "Bahrain", "zh": "巴林"},
    "BI": {"dial_code": "257", "en": "Burundi", "zh": "布隆迪"},
    "BJ": {"dial_code": "229", "en": "Benin", "zh": "贝宁"},
    "BM": {"dial_code": "1", "en": "Bermuda", "zh": "百慕大"},
    "BN": {"dial_code": "673", "en": "Brunei", "zh": "文莱"},
    "BO": {"dial_code": "591", "en": "Bolivia", "zh": "玻利维亚"},
    "BR": {"dial_code": "55", "en": "Brazil", "zh": "巴西"},
    "BS": {"dial_code": "1", "en": "Bahamas", "zh": "巴哈马"},
    "BT": {"dial_code": "975", "en": "Bhutan", "zh": "不丹"},
    "BW": {"dial_code": "267", "en": "Botswana", "zh": "博茨瓦纳"},
    "BY": {"dial_code": "375", "en": "Belarus", "zh": "白俄罗斯"},
    "BZ": {"dial_code": "501", "en": "Belize", "zh": "伯利兹"},
    "CA": {"dial_code": "1", "en": "Canada", "zh": "加拿大"},
    "CD": {"dial_code": "243", "en": "Democratic Republic of the Congo", "zh": "刚果民主共和国"},
    "CF": {"dial_code": "236", "en": "Central African Republic", "zh": "中非共和国"},
    "CG": {"dial_code": "242", "en": "Congo", "zh": "刚果共和国"},
    "CH": {"dial_code": "41", "en": "Switzerland", "zh": "瑞士"},
    "CI": {"dial_code": "225", "en": "Côte d'Ivoire", "zh": "科特迪瓦"},
    "CL": {"dial_code": "56", "en": "Chile", "zh": "智利"},
    "CM": {"dial_code": "237", "en": "Cameroon", "zh": "喀麦隆"},
    "CN": {"dial_code": "86", "en": "China", "zh": "中国"},
    "CO": {"dial_code": "57", "en": "Colombia", "zh": "哥伦比亚"},
    "CR": {"dial_code": "506", "en": "Costa Rica", "zh": "哥斯达黎加"},
    "CU": {"dial_code": "53", "en": "Cuba", "zh": "古巴"},
    "CV": {"dial_code": "238", "en": "Cape Verde", "zh": "佛得角"},
    "CW": {"dial_code": "599", "en": "Curaçao", "zh": "库拉索"},
    "CY": {"dial_code": "357", "en": "Cyprus", "zh": "塞浦路斯"},
    "CZ": {"dial_code": "420", "en": "Czechia", "zh": "捷克"},
    "DE": {"dial_code": "49", "en": "Germany", "zh": "德国"},
    "DJ": {"dial_code": "253", "en": "Djibouti", "zh": "吉布提"},
    "DK": {"dial_code": "45", "en": "Denmark", "zh": "丹麦"},
    "DM": {"dial_code": "1", "en": "Dominica", "zh": "多米尼克"},
    "DO": {"dial_code": "1", "en": "Dominican Republic", "zh": "多米尼加共和国"},
    "DZ": {"dial_code": "213", "en": "Algeria", "zh": "阿尔及利亚"},
    "EC": {"dial_code": "593", "en": "Ecuador", "zh": "厄瓜多尔"},
    "EE": {"dial_code": "372", "en": "Estonia", "zh": "爱沙尼亚"},
    "EG": {"dial_code": "20", "en": "Egypt", "zh": "埃及"},
    "ER": {"dial_code": "291", "en": "Eritrea", "zh": "厄立特里亚"},
    "ES": {"dial_code": "34", "en": "Spain", "zh": "西班牙"},
    "ET": {"dial_code": "251", "en": "Ethiopia", "zh": "埃塞俄比亚"},
    "FI": {"dial_code": "358", "en": "Finland", "zh": "芬兰"},
    "FJ": {"dial_code": "679", "en": "Fiji", "zh": "斐济"},
    "FM": {"dial_code": "691", "en": "Micronesia", "zh": "密克罗尼西亚"},
    "FO": {"dial_code": "298", "en": "Faroe Islands", "zh": "法罗群岛"},
    "FR": {"dial_code": "33", "en": "France", "zh": "法国"},
    "GA": {"dial_code": "241", "en": "Gabon", "zh": "加蓬"},
    "GB": {"dial_code": "44", "en": "United Kingdom", "zh": "英国"},
    "GD": {"dial_code": "1", "en": "Grenada", "zh": "格林纳达"},
    "GE": {"dial_code": "995", "en": "Georgia", "zh": "格鲁吉亚"},
    "GF": {"dial_code": "594", "en": "French Guiana", "zh": "法属圭亚那"},
    "GH": {"dial_code": "233", "en": "Ghana", "zh": "加纳"},
    "GI": {"dial_code": "350", "en": "Gibraltar", "zh": "直布罗陀"},
    "GL": {"dial_code": "299", "en": "Greenland", "zh": "格陵兰"},
    "GM": {"dial_code": "220", "en": "Gambia", "zh": "冈比亚"},
    "GN": {"dial_code": "224", "en": "Guinea", "zh": "几内亚"},
    "GP": {"dial_code": "590", "en": "Guadeloupe", "zh": "瓜德罗普"},
    "GQ": {"dial_code": "240", "en": "Equatorial Guinea", "zh": "赤道几内亚"},
    "GR": {"dial_code": "30", "en": "Greece", "zh": "希腊"},
    "GT": {"dial_code": "502", "en": "Guatemala", "zh": "危地马拉"},
    "GU": {"dial_code": "1", "en": "Guam", "zh": "关岛"},
    "GW": {"dial_code": "245", "en": "Guinea-Bissau", "zh": "几内亚比绍"},
    "GY": {"dial_code": "592", "en": "Guyana", "zh": "圭亚那"},
    "HK": {"dial_code": "852", "en": "Hong Kong", "zh": "中国香港"},
    "HN": {"dial_code": "504", "en": "Honduras", "zh": "洪都拉斯"},
    "HR": {"dial_code": "385", "en": "Croatia", "zh": "克罗地亚"},
    "HT": {"dial_code": "509", "en": "Haiti", "zh": "海地"},
    "HU": {"dial_code": "36", "en": "Hungary", "zh": "匈牙利"},
    "ID": {"dial_code": "62", "en": "Indonesia", "zh": "印度尼西亚"},
    "IE": {"dial_code": "353", "en": "Ireland", "zh": "爱尔兰"},
    "IL": {"dial_code": "972", "en": "Israel", "zh": "以色列"},
    "IN": {"dial_code": "91", "en": "India", "zh": "印度"},
    "IQ": {"dial_code": "964", "en": "Iraq", "zh": "伊拉克"},
    "IR": {"dial_code": "98", "en": "Iran", "zh": "伊朗"},
    "IS": {"dial_code": "354", "en": "Iceland", "zh": "冰岛"},
    "IT": {"dial_code": "39", "en": "Italy", "zh": "意大利"},
    "JM": {"dial_code": "1", "en": "Jamaica", "zh": "牙买加"},
    "JO": {"dial_code": "962", "en": "Jordan", "zh": "约旦"},
    "JP": {"dial_code": "81", "en": "Japan", "zh": "日本"},
    "KE": {"dial_code": "254", "en": "Kenya", "zh": "肯尼亚"},
    "KG": {"dial_code": "996", "en": "Kyrgyzstan", "zh": "吉尔吉斯斯坦"},
    "KH": {"dial_code": "855", "en": "Cambodia", "zh": "柬埔寨"},
    "KM": {"dial_code": "269", "en": "Comoros", "zh": "科摩罗"},
    "KN": {"dial_code": "1", "en": "Saint Kitts and Nevis", "zh": "圣基茨和尼维斯"},
    "KP": {"dial_code": "850", "en": "North Korea", "zh": "朝鲜"},
    "KR": {"dial_code": "82", "en": "South Korea", "zh": "韩国"},
    "KW": {"dial_code": "965", "en": "Kuwait", "zh": "科威特"},
    "KY": {"dial_code": "1", "en": "Cayman Islands", "zh": "开曼群岛"},
    "KZ": {"dial_code": "7", "en": "Kazakhstan", "zh": "哈萨克斯坦"},
    "LA": {"dial_code": "856", "en": "Laos", "zh": "老挝"},
    "LB": {"dial_code": "961", "en": "Lebanon", "zh": "黎巴嫩"},
    "LC": {"dial_code": "1", "en": "Saint Lucia", "zh": "圣卢西亚"},
    "LI": {"dial_code": "423", "en": "Liechtenstein", "zh": "列支敦士登"},
    "LK": {"dial_code": "94", "en": "Sri Lanka", "zh": "斯里兰卡"},
    "LR": {"dial_code": "231", "en": "Liberia", "zh": "利比里亚"},
    "LS": {"dial_code": "266", "en": "Lesotho", "zh": "莱索托"},
    "LT": {"dial_code": "370", "en": "Lithuania", "zh": "立陶宛"},
    "LU": {"dial_code": "352", "en": "Luxembourg", "zh": "卢森堡"},
    "LV": {"dial_code": "371", "en": "Latvia", "zh": "拉脱维亚"},
    "LY": {"dial_code": "218", "en": "Libya", "zh": "利比亚"},
    "MA": {"dial_code": "212", "en": "Morocco", "zh": "摩洛哥"},
    "MD": {"dial_code": "373", "en": "Moldova", "zh": "摩尔多瓦"},
    "ME": {"dial_code": "382", "en": "Montenegro", "zh": "黑山"},
    "MG": {"dial_code": "261", "en": "Madagascar", "zh": "马达加斯加"},
    "MK": {"dial_code": "389", "en": "North Macedonia", "zh": "北马其顿"},
    "ML": {"dial_code": "223", "en": "Mali", "zh": "马里"},
    "MM": {"dial_code": "95", "en": "Myanmar", "zh": "缅甸"},
    "MN": {"dial_code": "976", "en": "Mongolia", "zh": "蒙古"},
    "MO": {"dial_code": "853", "en": "Macao", "zh": "中国澳门"},
    "MQ": {"dial_code": "596", "en": "Martinique", "zh": "马提尼克"},
    "MR": {"dial_code": "222", "en": "Mauritania", "zh": "毛里塔尼亚"},
    "MS": {"dial_code": "1", "en": "Montserrat", "zh": "蒙特塞拉特"},
    "MT": {"dial_code": "356", "en": "Malta", "zh": "马耳他"},
    "MU": {"dial_code": "230", "en": "Mauritius", "zh": "毛里求斯"},
    "MV": {"dial_code": "960", "en": "Maldives", "zh": "马尔代夫"},
    "MW": {"dial_code": "265", "en": "Malawi", "zh": "马拉维"},
    "MX": {"dial_code": "52", "en": "Mexico", "zh": "墨西哥"},
    "MY": {"dial_code": "60", "en": "Malaysia", "zh": "马来西亚"},
    "MZ": {"dial_code": "258", "en": "Mozambique", "zh": "莫桑比克"},
    "NA": {"dial_code": "264", "en": "Namibia", "zh": "纳米比亚"},
    "NC": {"dial_code": "687", "en": "New Caledonia", "zh": "新喀里多尼亚"},
    "NE": {"dial_code": "227", "en": "Niger", "zh": "尼日尔"},
    "NG": {"dial_code": "234", "en": "Nigeria", "zh": "尼日利亚"},
    "NI": {"dial_code": "505", "en": "Nicaragua", "zh": "尼加拉瓜"},
    "NL": {"dial_code": "31", "en": "Netherlands", "zh": "荷兰"},
    "NO": {"dial_code": "47", "en": "Norway", "zh": "挪威"},
    "NP": {"dial_code": "977", "en": "Nepal", "zh": "尼泊尔"},
    "NZ": {"dial_code": "64", "en": "New Zealand", "zh": "新西兰"},
    "OM": {"dial_code": "968", "en": "Oman", "zh": "阿曼"},
    "PA": {"dial_code": "507", "en": "Panama", "zh": "巴拿马"},
    "PE": {"dial_code": "51", "en": "Peru", "zh": "秘鲁"},
    "PF": {"dial_code": "689", "en": "French Polynesia", "zh": "法属波利尼西亚"},
    "PG": {"dial_code": "675", "en": "Papua New Guinea", "zh": "巴布亚新几内亚"},
    "PH": {"dial_code": "63", "en": "Philippines", "zh": "菲律宾"},
    "PK": {"dial_code": "92", "en": "Pakistan", "zh": "巴基斯坦"},
    "PL": {"dial_code": "48", "en": "Poland", "zh": "波兰"},
    "PR": {"dial_code": "1", "en": "Puerto Rico", "zh": "波多黎各"},
    "PS": {"dial_code": "970", "en": "Palestine", "zh": "巴勒斯坦"},
    "PT": {"dial_code": "351", "en": "Portugal", "zh": "葡萄牙"},
    "PY": {"dial_code": "595", "en": "Paraguay", "zh": "巴拉圭"},
    "QA": {"dial_code": "974", "en": "Qatar", "zh": "卡塔尔"},
    "RE": {"dial_code": "262", "en": "Réunion", "zh": "留尼汪"},
    "RO": {"dial_code": "40", "en": "Romania", "zh": "罗马尼亚"},
    "RS": {"dial_code": "381", "en": "Serbia", "zh": "塞尔维亚"},
    "RU": {"dial_code": "7", "en": "Russia", "zh": "俄罗斯"},
    "RW": {"dial_code": "250", "en": "Rwanda", "zh": "卢旺达"},
    "SA": {"dial_code": "966", "en": "Saudi Arabia", "zh": "沙特阿拉伯"},
    "SC": {"dial_code": "248", "en": "Seychelles", "zh": "塞舌尔"},
    "SD": {"dial_code": "249", "en": "Sudan", "zh": "苏丹"},
    "SE": {"dial_code": "46", "en": "Sweden", "zh": "瑞典"},
    "SG": {"dial_code": "65", "en": "Singapore", "zh": "新加坡"},
    "SI": {"dial_code": "386", "en": "Slovenia", "zh": "斯洛文尼亚"},
    "SK": {"dial_code": "421", "en": "Slovakia", "zh": "斯洛伐克"},
    "SL": {"dial_code": "232", "en": "Sierra Leone", "zh": "塞拉利昂"},
    "SM": {"dial_code": "378", "en": "San Marino", "zh": "圣马力诺"},
    "SN": {"dial_code": "221", "en": "Senegal", "zh": "塞内加尔"},
    "SO": {"dial_code": "252", "en": "Somalia", "zh": "索马里"},
    "SR": {"dial_code": "597", "en": "Suriname", "zh": "苏里南"},
    "SS": {"dial_code": "211", "en": "South Sudan", "zh": "南苏丹"},
    "SV": {"dial_code": "503", "en": "El Salvador", "zh": "萨尔瓦多"},
    "SX": {"dial_code": "1", "en": "Sint Maarten", "zh": "荷属圣马丁"},
    "SY": {"dial_code": "963", "en": "Syria", "zh": "叙利亚"},
    "SZ": {"dial_code": "268", "en": "Eswatini", "zh": "斯威士兰"},
    "TC": {"dial_code": "1", "en": "Turks and Caicos Islands", "zh": "特克斯和凯科斯群岛"},
    "TD": {"dial_code": "235", "en": "Chad", "zh": "乍得"},
    "TG": {"dial_code": "228", "en": "Togo", "zh": "多哥"},
    "TH": {"dial_code": "66", "en": "Thailand", "zh": "泰国"},
    "TJ": {"dial_code": "992", "en": "Tajikistan", "zh": "塔吉克斯坦"},
    "TL": {"dial_code": "670", "en": "Timor-Leste", "zh": "东帝汶"},
    "TM": {"dial_code": "993", "en": "Turkmenistan", "zh": "土库曼斯坦"},
    "TN": {"dial_code": "216", "en": "Tunisia", "zh": "突尼斯"},
    "TO": {"dial_code": "676", "en": "Tonga", "zh": "汤加"},
    "TR": {"dial_code": "90", "en": "Türkiye", "zh": "土耳其"},
    "TT": {"dial_code": "1", "en": "Trinidad and Tobago", "zh": "特立尼达和多巴哥"},
    "TW": {"dial_code": "886", "en": "Taiwan", "zh": "中国台湾"},
    "TZ": {"dial_code": "255", "en": "Tanzania", "zh": "坦桑尼亚"},
    "UA": {"dial_code": "380", "en": "Ukraine", "zh": "乌克兰"},
    "UG": {"dial_code": "256", "en": "Uganda", "zh": "乌干达"},
    "US": {"dial_code": "1", "en": "United States", "zh": "美国"},
    "UY": {"dial_code": "598", "en": "Uruguay", "zh": "乌拉圭"},
    "UZ": {"dial_code": "998", "en": "Uzbekistan", "zh": "乌兹别克斯坦"},
    "VC": {"dial_code": "1", "en": "Saint Vincent and the Grenadines", "zh": "圣文森特和格林纳丁斯"},
    "VE": {"dial_code": "58", "en": "Venezuela", "zh": "委内瑞拉"},
    "VG": {"dial_code": "1", "en": "British Virgin Islands", "zh": "英属维尔京群岛"},
    "VI": {"dial_code": "1", "en": "U.S. Virgin Islands", "zh": "美属维尔京群岛"},
    "VN": {"dial_code": "84", "en": "Vietnam", "zh": "越南"},
    "VU": {"dial_code": "678", "en": "Vanuatu", "zh": "瓦努阿图"},
    "WS": {"dial_code": "685", "en": "Samoa", "zh": "萨摩亚"},
    "XK": {"dial_code": "383", "en": "Kosovo", "zh": "科索沃"},
    "YE": {"dial_code": "967", "en": "Yemen", "zh": "也门"},
    "ZA": {"dial_code": "27", "en": "South Africa", "zh": "南非"},
    "ZM": {"dial_code": "260", "en": "Zambia", "zh": "赞比亚"},
    "ZW": {"dial_code": "263", "en": "Zimbabwe", "zh": "津巴布韦"},
}


def country_by_iso2(iso2: str) -> dict[str, str] | None:
    return COUNTRY_BY_ISO2.get((iso2 or "").strip().upper())


def iso2_by_name(*names: str) -> str:
    """Resolve an ISO2 code from English or Chinese provider names."""
    values = {
        (name or "").strip().casefold()
        for name in names
        if (name or "").strip()
    }
    if not values:
        return ""
    for iso2, info in COUNTRY_BY_ISO2.items():
        known = {info["en"].casefold(), info["zh"]}
        if values & known:
            return iso2
    return ""
